name: pre-commit
description: run pre-commit and optionally commit back to the pull request
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  token:
    description: github token to clone / push with
    required: false
  git_user_name:
    description: github user name to push with
    required: false
    default: 'pre-commit'
  git_user_email:
    description: github user email to push with
    required: false
    default: 'pre-commit@example.com'

runs:
  using: 'node12'
  main: 'dist/index.js'
